version: '3'
services: 
    frontend:
        image: eauctionathackfse/eauction-frontend-aws
        build: 
            context: .
            dockerfile: Dockerfile
        command: npm run start
        container_name: eauction-frontend
        ports:
            - "3000:3000"        
        volumes: 
            - ./:/frontend
            - /frontend/node_modules
networks:
  default:
    external:
      name: eauctionHouseNet
